// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2DDA.Data;

#nullable disable

namespace Parcial2DDA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119223420_agregarMedicion")]
    partial class agregarMedicion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parcial2DDA.Models.Medicion", b =>
                {
                    b.Property<string>("Huella")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Huella");

                    b.ToTable("Mediciones");
                });
#pragma warning restore 612, 618
        }
    }
}
